# Generated by Django 3.0.2 on 2020-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cctv_data',
            name='sisul',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='report',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='article_scrap',
            name='scrap_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cctv_data',
            name='big_addr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cctv_data',
            name='cctv_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cctv_data',
            name='cctv_yn',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cctv_data',
            name='small_addr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='home',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
